fix: use node.rest.loadTracks instead of manager.search
- Fix search.service.js to use node.rest.loadTracks() API
- Fix autoplay.service.js to use node.rest.loadTracks() API
- Add getAvailableNode() helper function to get connected node
- Update query format to use prefix format (ytsearch:, ytmsearch:, spsearch:)
- Fixes TypeError: manager.search is not a function